### ISSUE TITLE
Underscores in FDSN identifiers

### ISSUE THREAD

**Issue by krischer** [iris-edu/mseed3-evaluation#4]
Discussion branched off #2. Concerns DRAFT20170622.

@krischer

> Maybe allow underscores and dashes in all the codes? Might be useful for example for somewhat semantic names of sensors arranged in a grid.

@chad-iris 

> Hhmm, interesting. It could make for cluttered looking IDs, but I see the use. Curious what others think, I'll ask around the DMC.

**Comment by chad-earthscope** [comment]
>> My point mainly is that it is a little weird to have 3 different separators ( . : and _ ) in what is a pretty short string. If we adopt Lion's underscores, then just use that for the existing : separator. Or use : instead of underscore. They are just delimiters, they don't need to be all different.

>The "." is a separator and the ":" is a separator, but the "-" (or "_") are not separators, they are part of the code. At least that was my understanding of the proposal.
>
> You could argue that the loc:chan separation should be done with a ".", the idea was that it's treated differently because it can be empty. There is a simplicity to knowing that, in the FDSN: namespace, there are always two dots, you can always parse the three required codes (net,sta,chan). Then the chan may be decorated with a location (how it's done in StationXML). Of course there could always be three dots, where the loc is sometimes empty, I just haven't see any other identifier systems that have back-to-back separators. But it's not impossible. Worst case is sometimes two dots, sometimes three dots, so I tried to avoid that.

Hhmm, after writing some code to see how these identifiers could be handled, I find dealing with the sometimes-there and sometimes-not colon (:) separator more awkward than I was hoping.  One practical issue is that matching the identifiers with globbing wildcards, which I would expect to be quite useful, is non-trivial in the case of matching all location codes.  For example, "FDSN:net.sta.*:chan" does not match "FDSN:net.sta.chan".  It'd certainly be simpler to always have 4 fields separated with the same delimiter.
